/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package costazul;

/**
 *
 * @author Guillermo
 */
public class Entrada extends javax.swing.JPanel {

    /**
     * Creates new form Entrada
     */
    private Inicio inicio;
    public Entrada(Inicio inicio) {
        initComponents();
        this.inicio=inicio;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSi = new javax.swing.JButton();
        BtnNo = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSi.setBackground(new java.awt.Color(28, 28, 28));
        BtnSi.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        BtnSi.setForeground(new java.awt.Color(255, 255, 255));
        BtnSi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/costazul/FondoBoton.jpg"))); // NOI18N
        BtnSi.setText("CON VEHÍCULO");
        BtnSi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiActionPerformed(evt);
            }
        });
        add(BtnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 750, 400, 150));

        BtnNo.setBackground(new java.awt.Color(28, 28, 28));
        BtnNo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        BtnNo.setForeground(new java.awt.Color(255, 255, 255));
        BtnNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/costazul/FondoBoton.jpg"))); // NOI18N
        BtnNo.setText("SIN VEHÍCULO");
        BtnNo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNoMouseClicked(evt);
            }
        });
        BtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNoActionPerformed(evt);
            }
        });
        add(BtnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 400, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNoActionPerformed
        inicio.IniciarInterfazTienda();
    }//GEN-LAST:event_BtnNoActionPerformed

    private void BtnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiActionPerformed
        inicio.InicioEsta();
    }//GEN-LAST:event_BtnSiActionPerformed

    private void BtnNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNo;
    private javax.swing.JButton BtnSi;
    // End of variables declaration//GEN-END:variables
}
