/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package costazul;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Guillermo
 */
public class Estacionamiento extends javax.swing.JPanel {

    /**
     * Creates new form Estacionamiento
     */
    private InicioEstacionamiento EstacionamientoInicio;
    public Estacionamiento(InicioEstacionamiento EstacionamientoInicio) {
        initComponents();
        this.EstacionamientoInicio=EstacionamientoInicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSecA = new javax.swing.JButton();
        BtnSecB = new javax.swing.JButton();
        BtnSecC = new javax.swing.JButton();
        BtnSecD = new javax.swing.JButton();
        BtnSecE = new javax.swing.JButton();
        BtnSecF = new javax.swing.JButton();
        LblPuesto = new javax.swing.JLabel();
        TFPuesto = new javax.swing.JTextField();
        LblEntrada = new javax.swing.JLabel();
        TFEntrada = new javax.swing.JTextField();
        LblSalida = new javax.swing.JLabel();
        TFSalida = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSecA.setText("SECCIÓN A");
        BtnSecA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSecAActionPerformed(evt);
            }
        });
        add(BtnSecA, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 35, 400, 115));

        BtnSecB.setText("SECCIÓN B");
        BtnSecB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSecBActionPerformed(evt);
            }
        });
        add(BtnSecB, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 168, 400, 115));

        BtnSecC.setText("SECCIÓN C");
        BtnSecC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSecCActionPerformed(evt);
            }
        });
        add(BtnSecC, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 301, 400, 115));

        BtnSecD.setText("SECCIÓN D");
        BtnSecD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSecDActionPerformed(evt);
            }
        });
        add(BtnSecD, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 434, 400, 115));

        BtnSecE.setText("SECCIÓN E");
        BtnSecE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSecEActionPerformed(evt);
            }
        });
        add(BtnSecE, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 567, 400, 115));

        BtnSecF.setText("SECCIÓN F");
        BtnSecF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSecFActionPerformed(evt);
            }
        });
        add(BtnSecF, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 700, 400, 115));

        LblPuesto.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LblPuesto.setText("Puesto");
        add(LblPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 820, -1, 56));

        TFPuesto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        add(TFPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 820, 557, 56));

        LblEntrada.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LblEntrada.setText("Entrada");
        add(LblEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 900, -1, 56));

        TFEntrada.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        add(TFEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 900, 557, 56));

        LblSalida.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LblSalida.setText("Salida");
        add(LblSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 970, -1, 56));

        TFSalida.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        add(TFSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 970, 557, 56));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSecAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSecAActionPerformed
        EstacionamientoInicio.seccion='A';
        EstacionamientoInicio.puesto=Integer.parseInt(TFPuesto.getText());
        EstacionamientoInicio.horaEntrada=TFEntrada.getText();
        EstacionamientoInicio.horaSalida=TFSalida.getText();
        EstacionamientoInicio.addVehicle();
    }//GEN-LAST:event_BtnSecAActionPerformed

    private void BtnSecBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSecBActionPerformed
        EstacionamientoInicio.seccion='B';
        EstacionamientoInicio.addVehicle();
    }//GEN-LAST:event_BtnSecBActionPerformed

    private void BtnSecCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSecCActionPerformed
        EstacionamientoInicio.seccion='C';
        EstacionamientoInicio.addVehicle();
    }//GEN-LAST:event_BtnSecCActionPerformed

    private void BtnSecDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSecDActionPerformed
        EstacionamientoInicio.seccion='D';
        EstacionamientoInicio.addVehicle();
    }//GEN-LAST:event_BtnSecDActionPerformed

    private void BtnSecEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSecEActionPerformed
        EstacionamientoInicio.seccion='E';
        EstacionamientoInicio.addVehicle();
    }//GEN-LAST:event_BtnSecEActionPerformed

    private void BtnSecFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSecFActionPerformed
        EstacionamientoInicio.seccion='F';
        EstacionamientoInicio.addVehicle();
    }//GEN-LAST:event_BtnSecFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSecA;
    private javax.swing.JButton BtnSecB;
    private javax.swing.JButton BtnSecC;
    private javax.swing.JButton BtnSecD;
    private javax.swing.JButton BtnSecE;
    private javax.swing.JButton BtnSecF;
    private javax.swing.JLabel LblEntrada;
    private javax.swing.JLabel LblPuesto;
    private javax.swing.JLabel LblSalida;
    private javax.swing.JTextField TFEntrada;
    private javax.swing.JTextField TFPuesto;
    private javax.swing.JTextField TFSalida;
    // End of variables declaration//GEN-END:variables
}
