/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package costazul;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillermo
 */
public class PantallaCompraPago extends javax.swing.JPanel {

    /**
     * Creates new form PantallaCompraPago
     */
    
    Inicio inicio;
    public PantallaCompraPago(Inicio inicio) {
        initComponents();
        cargarElementos();
        this.inicio=inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        CBPagos = new javax.swing.JComboBox<>();
        LblTienda1 = new javax.swing.JLabel();
        RBPresencial = new javax.swing.JRadioButton();
        RBOnline = new javax.swing.JRadioButton();
        BtnPagos = new javax.swing.JButton();
        LblCedula = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblApellido = new javax.swing.JLabel();
        PanelContenido = new javax.swing.JPanel();
        LblTienda = new javax.swing.JLabel();
        LblProducto1 = new javax.swing.JLabel();
        LblProducto2 = new javax.swing.JLabel();
        LblVehiculo = new javax.swing.JLabel();
        LblProducto3 = new javax.swing.JLabel();
        LblTotal = new javax.swing.JLabel();
        LblEncargado = new javax.swing.JLabel();
        BtnEntrar = new javax.swing.JButton();
        LblMarca = new javax.swing.JLabel();
        LblColor = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBPagos.setBackground(new java.awt.Color(0, 153, 153));
        CBPagos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        CBPagos.setForeground(new java.awt.Color(255, 255, 255));
        CBPagos.setBorder(null);
        CBPagos.setEnabled(false);
        CBPagos.setOpaque(false);
        CBPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBPagosMouseClicked(evt);
            }
        });
        CBPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPagosActionPerformed(evt);
            }
        });
        jPanel1.add(CBPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 510, 70));

        LblTienda1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LblTienda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTienda1.setText("METODO DE PAGO");
        jPanel1.add(LblTienda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 700, 70));

        RBPresencial.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        RBPresencial.setText("Presencial");
        RBPresencial.setOpaque(false);
        RBPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPresencialActionPerformed(evt);
            }
        });
        jPanel1.add(RBPresencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 217, 110));

        RBOnline.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        RBOnline.setText("Online");
        RBOnline.setOpaque(false);
        RBOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBOnlineActionPerformed(evt);
            }
        });
        jPanel1.add(RBOnline, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, 110));

        BtnPagos.setBackground(new java.awt.Color(28, 28, 28));
        BtnPagos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BtnPagos.setForeground(new java.awt.Color(255, 255, 255));
        BtnPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/costazul/FondoBoton.jpg"))); // NOI18N
        BtnPagos.setText("PAGAR");
        BtnPagos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPagosMouseClicked(evt);
            }
        });
        BtnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPagosActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 720, 250, 70));

        LblCedula.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LblCedula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblCedula.setText("Cedula");
        jPanel1.add(LblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 650, -1));

        LblNombre.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblNombre.setText("Nombre");
        jPanel1.add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 650, -1));

        LblApellido.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LblApellido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblApellido.setText("Apellido");
        jPanel1.add(LblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 650, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 140, 700, 800));

        PanelContenido.setOpaque(false);
        PanelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblTienda.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LblTienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTienda.setText("TIENDA");
        PanelContenido.add(LblTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 970, 70));

        LblProducto1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LblProducto1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblProducto1.setText("PRODUCTOS");
        PanelContenido.add(LblProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 700, -1));

        LblProducto2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LblProducto2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblProducto2.setText("PRODUCTOS");
        PanelContenido.add(LblProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 700, -1));

        LblVehiculo.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LblVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblVehiculo.setText("Vehiculo");
        PanelContenido.add(LblVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 700, -1));

        LblProducto3.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LblProducto3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblProducto3.setText("PRODUCTOS");
        PanelContenido.add(LblProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 700, -1));

        LblTotal.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblTotal.setText("TOTAL");
        LblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelContenido.add(LblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, 660, -1));

        LblEncargado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LblEncargado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblEncargado.setText("Encargado");
        PanelContenido.add(LblEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 510, -1));

        BtnEntrar.setBackground(new java.awt.Color(28, 28, 28));
        BtnEntrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BtnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/costazul/FondoBoton.jpg"))); // NOI18N
        BtnEntrar.setText("CARGAR");
        BtnEntrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEntrarMouseClicked(evt);
            }
        });
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });
        PanelContenido.add(BtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 710, 250, 70));

        LblMarca.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LblMarca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblMarca.setText("Marca");
        PanelContenido.add(LblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 700, -1));

        LblColor.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LblColor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblColor.setText("Color");
        PanelContenido.add(LblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 700, -1));

        jPanel2.add(PanelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 970, 850));

        BtnVolver.setBackground(new java.awt.Color(51, 51, 51));
        BtnVolver.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/costazul/FondoBoton.jpg"))); // NOI18N
        BtnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVolver.setLabel("VOLVER");
        BtnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnVolverMouseClicked(evt);
            }
        });
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1770, 990, 140, 60));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/costazul/FondoCompraPago.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel2.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));
    }// </editor-fold>//GEN-END:initComponents

    
    private void CrearArchivo(){
        File registro = new File("./src/costazul/arbol/Compras.txt");
            if (!registro.exists()) {
                try {
                    registro.createNewFile();
                    System.out.println("se creo el archivo");
                } catch (IOException ex) {
                    Logger.getLogger(InicioEstacionamiento.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }
    
    
    public void cargarElementos(){
        
        
        LblProducto1.setText(Usuario.producto1+"$"); 
        LblProducto2.setText(Usuario.producto2+"$"); 
        LblProducto3.setText(Usuario.producto3+"$");
        LblTienda.setText(Usuario.Tienda);
        LblEncargado.setText(Usuario.Encargado);
        LblTotal.setText("Total= "+Usuario.totalPago+"$");
        LblVehiculo.setText("Vehiculo: "+Usuario.tipoDeVehiculo+" - "+Usuario.marcaVehiculo);
        LblMarca.setText("Matricula: "+Usuario.matricula);
        LblColor.setText("Color: "+Usuario.colorVehiculo);
        LblNombre.setText("Nombre: "+Usuario.nombre);
        LblApellido.setText("Apellido: "+Usuario.apellido);
        LblCedula.setText("Cedula: "+Usuario.cedula);
    }
    
    private void BtnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEntrarMouseClicked

    }//GEN-LAST:event_BtnEntrarMouseClicked

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        cargarElementos();
        //LblRubro.setText("Rubro: "+NodoActual.Rubro);
    }//GEN-LAST:event_BtnEntrarActionPerformed

    private void RBPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPresencialActionPerformed
        CBPagos.removeAllItems();
        CBPagos.addItem("Efectivo");
        CBPagos.addItem("Crédito");
        CBPagos.addItem("Débito");
        CBPagos.addItem("Dios se lo pague *Salir corriendo*");
        CBPagos.enable(true);
        BtnPagos.enable(true);
        cargarElementos();
    }//GEN-LAST:event_RBPresencialActionPerformed

    private void RBOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBOnlineActionPerformed
        CBPagos.removeAllItems();
        CBPagos.addItem("Transferecia");
        CBPagos.addItem("PagoMovil");
        CBPagos.enable(true);
        BtnPagos.enable(true);
        cargarElementos();
    }//GEN-LAST:event_RBOnlineActionPerformed

    private void BtnPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPagosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPagosMouseClicked

    private void BtnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPagosActionPerformed
        try {
            CrearArchivo();
            String registro= Usuario.nombre+"-"+Usuario.apellido+"-"+Usuario.cedula+"-"+Usuario.colorVehiculo+"-"+Usuario.marcaVehiculo+"-"+Usuario.matricula+"-"+Usuario.horaEntrada+"-"+Usuario.horaSalida+"-"+Usuario.tipoDeVehiculo+"-"+Usuario.puesto+"-"+Usuario.seccion+"-"+Usuario.Tienda+"-"+Usuario.Encargado+"-"+Usuario.producto1+"-"+Usuario.producto2+"-"+Usuario.producto3+"-"+Usuario.totalPago+"\n";////////////////////////////////////////
            Files.write(Paths.get("./src/costazul/arbol/Compras.txt"), registro.getBytes(), StandardOpenOption.APPEND);  
            inicio.InicioFinal();
            //JOptionPane.showMessageDialog(this, "Compra Realizada con exito! \n \n Somos Parque Costazul \n Gracias por preferirnos");
        } catch (IOException ex) {
            Logger.getLogger(PantallaCompraPago.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_BtnPagosActionPerformed

    private void CBPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPagosActionPerformed
        
        BtnPagos.enable();
    }//GEN-LAST:event_CBPagosActionPerformed

    private void CBPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBPagosMouseClicked
        
        BtnPagos.enable();
    }//GEN-LAST:event_CBPagosMouseClicked

    private void BtnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVolverMouseClicked

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        inicio.volverEsta();
    }//GEN-LAST:event_BtnVolverActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JButton BtnPagos;
    private javax.swing.JButton BtnVolver;
    public javax.swing.JComboBox<String> CBPagos;
    private javax.swing.JLabel LblApellido;
    private javax.swing.JLabel LblCedula;
    private javax.swing.JLabel LblColor;
    private javax.swing.JLabel LblEncargado;
    private javax.swing.JLabel LblMarca;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblProducto1;
    private javax.swing.JLabel LblProducto2;
    private javax.swing.JLabel LblProducto3;
    private javax.swing.JLabel LblTienda;
    private javax.swing.JLabel LblTienda1;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JLabel LblVehiculo;
    private javax.swing.JPanel PanelContenido;
    private javax.swing.JRadioButton RBOnline;
    private javax.swing.JRadioButton RBPresencial;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
